### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by emmysteven** [ApoorvTyagi/ApoorvTyagi#1]
Hi 👋🏻

You have a nice GitHub profile, and it will look a lot better if you fix the following broken links:
- Java
- MySQL
- Python
- Docker
- C
- C++
- Android

Overall you profile rocks!
Happy new year 🎉

**Comment by ApoorvTyagi** [comment]
Hey @emmysteven 

Thanks for reporting the issue. I have fixed/updated all the broken links hence closing this issue.

Happy new year to you too 🎊🎉

**Comment by ApoorvTyagi** [comment]
Hey @emmysteven

Thanks for reporting the issue. I have fixed/updated all the broken links hence closing this issue.

Happy new year to you too 🎊🎉

**Comment by emmysteven** [comment]
You are welcome!
